export const CONSOLE_LOG = "console_log";

// authentication types

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_FRIENDS = "GET_FRIENDS";
export const FRIENDS_LOADED = "FRIENDS_LOADED";
export const LOAD_FRIENDS_ERROR = "LOAD_FRIENDS_ERROR";

export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const CONVERSATIONS_LOADED = "CONVERSATIONS_LOADED";
export const LOAD_CONVERSATIONS_ERROR = "LOAD_CONVERSATIONS_ERROR";

export const GET_MESSAGES = "GET_MESSAGES";
export const MESSAGES_LOADED = "MESSAGES_LOADED";
export const LOAD_MESSAGES_ERROR = "LOAD_MESSAGES_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
